MIN_MINS_BETWEEN_CLASSES = 10

OBJECTIVE_CREDITS_PER_PROFESSOR = 15
OBJECTIVE_WEIGHT_PER_PROFESSOR  = 3 * OBJECTIVE_CREDITS_PER_PROFESSOR

FORCE_LAB_ON_ONE_DAY      = True
ATTEMPT_EVEN_DISTRIBUTION = True

GENERATION_CHECK_SLEEP_S = 0.2